-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 01:21:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stimulus_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stimulus_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stimulus_bd` DEFAULT CHARACTER SET utf8 ;
USE `stimulus_bd`;

DROP DATABASE stimulus_bd;
-- -----------------------------------------------------
-- Table `stimulus_bd`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`responsavel` (
  `id_responsavel` INT NULL AUTO_INCREMENT,
  `nome_responsavel` VARCHAR(45) NULL,
  `email_responsavel` VARCHAR(45) NULL,
  `senha_responsavel` VARCHAR(45) NULL,
  `data_nascimento_responsavel` DATETIME NULL,
  PRIMARY KEY (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stimulus_bd`.`fase_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`fase_doenca` (
  `idfase_doenca` INT NOT NULL AUTO_INCREMENT,
  `fase_doenca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfase_doenca`))
ENGINE = InnoDB;

INSERT INTO fase_doenca VALUES (null,'Leve');
INSERT INTO fase_doenca VALUES (null,'Moderada');
INSERT INTO fase_doenca VALUES (null,'Grave');
-- -----------------------------------------------------
-- Table `stimulus_bd`.`portador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`portador` (
  `id_portador` INT NOT NULL AUTO_INCREMENT,
  `nome_portador` VARCHAR(45) BINARY NULL,
  `data_nascimento_portador` DATE NULL,
  `quantidade_filhos` INT NULL,
  `responsavel_id_responsavel` INT NOT NULL,
  `fase_doenca_idfase_doenca` INT NOT NULL,
  `cpf_portador` INT NOT NULL,
  PRIMARY KEY (`id_portador`),
  INDEX `fk_portador_responsavel1_idx` (`responsavel_id_responsavel` ASC),
  INDEX `fk_portador_fase_doenca1_idx` (`fase_doenca_idfase_doenca` ASC),
  CONSTRAINT `fk_portador_responsavel1`
    FOREIGN KEY (`responsavel_id_responsavel`)
    REFERENCES `stimulus_bd`.`responsavel` (`id_responsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portador_fase_doenca1`
    FOREIGN KEY (`fase_doenca_idfase_doenca`)
    REFERENCES `stimulus_bd`.`fase_doenca` (`idfase_doenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stimulus_bd`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `email_administrador` VARCHAR(45) NULL,
  `senha_administrador` VARCHAR(45) NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stimulus_bd`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`parentesco` (
  `idparentesco` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idparentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stimulus_bd`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`familiar` (
  `idfamiliar` INT NOT NULL,
  `nome_familiar` VARCHAR(45) NULL,
  `data_nascimento_familiar` DATETIME NULL,
  `foto_familiar` VARCHAR(45) NULL,
  `parentesco_idparentesco` INT NOT NULL,
  `portador_id_portador` INT NOT NULL,
  PRIMARY KEY (`idfamiliar`),
  INDEX `fk_familiar_parentesco1_idx` (`parentesco_idparentesco` ASC),
  INDEX `fk_familiar_portador1_idx` (`portador_id_portador` ASC),
  CONSTRAINT `fk_familiar_parentesco1`
    FOREIGN KEY (`parentesco_idparentesco`)
    REFERENCES `stimulus_bd`.`parentesco` (`idparentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_portador1`
    FOREIGN KEY (`portador_id_portador`)
    REFERENCES `stimulus_bd`.`portador` (`id_portador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stimulus_bd`.`cenarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stimulus_bd`.`cenarios` (
  `idcenarios` INT NOT NULL AUTO_INCREMENT,
  `path_cenario` VARCHAR(45) NULL,
  `portador_id_portador` INT NOT NULL,
  PRIMARY KEY (`idcenarios`),
  INDEX `fk_cenarios_portador1_idx` (`portador_id_portador` ASC),
  CONSTRAINT `fk_cenarios_portador1`
    FOREIGN KEY (`portador_id_portador`)
    REFERENCES `stimulus_bd`.`portador` (`id_portador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
